### PR TITLE
[URGENT] Fixing three bugs, see description below.

### PR DESCRIPTION
**Pull request by ricardobrito**
#### BUGS ####
[1] Mercadopago wasn’t getting the shipping cost on standard checkout
[2] MercadoPago wasn't getting the wrapping cost and discounts on standard checkout
[3] When using one step checkout and the user is not logged yet, the
javascript and css are not loading because **displayTopPayment is not working in this use case I mentioned, see steps to reproduce below:**
*1. Set one step checkout
2. Add a product into cart
3. Place order
4. You will be asked to login
5. Log in
6. Click on ‘Accept terms’
7. The css is not loaded and also the javascript since displayTopPayment not work either*

#### ENHANCEMENTS ####
[4] Including a parent css class to make sure css is only used by module MercadoPago
[5] Changing settings.tpl look and feel

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hi @ricardobrito,

Because you change a hook on this new version, you should create an upgrade file in order to register the new one without having to uninstall / reinstall the module.
You can have more information here:
http://doc.prestashop.com/display/PS15/Auto-updating+modules

Regards

**Comment by ricardobrito** [comment]
Hi @Quetzacoalt91,

Thanks for the heads up.
I included it, but don't know how to test it. Could you check if is it correct?

Best regards,
Ricardo

**Comment by Quetzacoalt91** [comment]
Hi @ricardobrito,

I just tried the upgrade and it works.
Add a zip of the module on 3.0.0, and a second one with the version 3.0.1, you will see the following notice:
capture du 2015-05-04 16 08 20

But I guess we could also unregister the previous hook during the upgrade. :)

Regards

**Comment by ricardobrito** [comment]
That's right :)
Done!
tks

**Comment by Quetzacoalt91** [comment]
Hi @ricardobrito,

Your PR has just been merged and the changes should be available from tomorrow.

Best regards

**Comment by ricardobrito** [comment]
@Quetzacoalt91 
Thanks for answering quickly! 
Best Regards!

**Pull request merged**
