### PR TITLE
[Urgent Fix] - Removing public key validation, module will stop working if not removed

### PR DESCRIPTION
**Pull request by ricardobrito**

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hi @ricardobrito,

I'm sorry but I don't have any four digits sent in the request:
capture du 2015-05-12 18 00 14

Can you investigate ?

Regards

**Comment by ricardobrito** [comment]
Hi Thomas,

It seems there is an error with your payment since you should also send
card_token_id. The card_token_id is only generated when all checkout data
is ok.

Your post should be like:

[image: Imágenes integradas 1]

Another hypothesis is javascript cache - can you also check if your
javascript has the four digits input? You should find this snippet on web
inspector:
[image: Imágenes integradas 2]

Regards,

*Ricardo Brito*
Software Engineer



2015-05-12 13:01 GMT-03:00 Thomas N <notifications@github.com>:

**Comment by ricardobrito** [comment]
Let me know if you need credentials and testing credit cards. Thanks

*Ricardo Brito*
Software Engineer



2015-05-12 13:52 GMT-03:00 Ricardo Brito de Souza <
ricardo.brito@mercadopago.com.br>:

**Comment by Quetzacoalt91** [comment]
Hi @ricardobrito,

I have the latest JS on my shop, nothing wrong on this side.

In case of error, I guess you would like to not send the form ? Because this is what I see on my side (my payment information are wrong, FYI)

Regards

**Comment by ricardobrito** [comment]
Hi @Quetzacoalt91 

Can you provide me the form data you are using so I can reproduce it?

**Comment by Quetzacoalt91** [comment]
Okay, the latest commit allowed me to complete the payment process.

I will not merge the PR, thanks.

**Pull request merged**
